### ISSUE TITLE
是否实现了csi 中的存储快照和存储扩容功能呢

### ISSUE THREAD

**Issue by aland-zhang** [chubaofs/chubaofs-csi#11]
你好，看了一下源码，没有发现实现 csi规范中的存储快照和存储扩容功能，是不是因为chubaofs 本身还不支持存储卷的快照和动态扩容功能呢？

**Comment by bladehliu** [comment]
自动存储扩容。快照TODO。谢谢！

**Comment by aland-zhang** [comment]
如果k8s pvc 的容量限制在100MB，那么数据到了100MB 是不是应该不让自动扩容，不让写入了。应该是让管理员把pvc 的值改大到200MB，存储卷才能扩容到200MB。这时用户才能继续往pv里写数据。

**Comment by awzhgw** [comment]
@aland-zhang  目前chubaofs vol 在存储资源满的时候，则该vol不会自动扩充dataPartition , 当这些dataPartition写满后，则用户写会报IO 错误.      这样有个好处，就是给了一部分空间给用户，让它可以继续写入。

**Comment by mervinkid** [comment]
@aland-zhang 

Thanks for your feedback.
We are considering adding support for automatic volume expansion.
ChubaoFS is currently a storage product that combines two storage types: file system and object storage. What this user sees is that they can use both POSIX-compatible file system interfaces and S3-compatible object storage interfaces.
Because there is no concept of capacity limitation in object storage, we believe that a more secure solution is to move closer to the experience of high-level object storage, which supports the automatic expansion to reduce the impact of capacity limitations on users.

**Comment by ssscottt** [comment]
> 你好，看了一下源码，没有发现实现 csi规范中的存储快照和存储扩容功能，是不是因为chubaofs 本身还不支持存储卷的快照和动态扩容功能呢？

Thank you for your feedback.
1. ChubaoFS itself supports expansion. We are going to upgrade the CSI spec to release 1.1+ and implement the `ControllerExpandVolume` interface in our CSI driver. 
2. ChubaoFS does not support snapshots.

**Comment by aland-zhang** [comment]
Thank you for your feedback！
